#-------------------------------------------------------------------------------
# Name:        DSCTravelAgency
# Purpose:     Allows clients of a travel agency to book a flight.
#
# Author:      Kenta Iwasaki
#
# Created:     29/05/2014
# Copyright:   (c) Kenta Iwasaki 2014
# Licence:     N/A
#-------------------------------------------------------------------------------

# PyQT Imports
from PyQt5 import QtCore, QtGui, QtWidgets

# UI Layout and Setup
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(811, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 191, 461))
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 171, 431))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 0, 1, 1)
        self.dobLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.dobLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dobLabel.setObjectName("dobLabel")
        self.gridLayout_2.addWidget(self.dobLabel, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.nameLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.nameLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.nameLabel.setObjectName("nameLabel")
        self.gridLayout_2.addWidget(self.nameLabel, 1, 1, 1, 1)
        self.idLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.idLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.idLabel.setObjectName("idLabel")
        self.gridLayout_2.addWidget(self.idLabel, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem, 5, 1, 1, 1)
        self.recentFlightsTable = QtWidgets.QTableWidget(self.gridLayoutWidget_2)
        self.recentFlightsTable.setAutoFillBackground(False)
        self.recentFlightsTable.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.recentFlightsTable.setProperty("showDropIndicator", False)
        self.recentFlightsTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.recentFlightsTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.recentFlightsTable.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.recentFlightsTable.setShowGrid(True)
        self.recentFlightsTable.setGridStyle(QtCore.Qt.SolidLine)
        self.recentFlightsTable.setCornerButtonEnabled(False)
        self.recentFlightsTable.setObjectName("recentFlightsTable")
        self.recentFlightsTable.setColumnCount(1)
        self.recentFlightsTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.recentFlightsTable.setHorizontalHeaderItem(0, item)
        self.recentFlightsTable.horizontalHeader().setMinimumSectionSize(27)
        self.gridLayout_2.addWidget(self.recentFlightsTable, 4, 0, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 3, 0, 1, 1)
        self.pointsLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.pointsLabel.setObjectName("pointsLabel")
        self.gridLayout_2.addWidget(self.pointsLabel, 3, 1, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(210, 10, 591, 461))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 571, 421))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.btnAirportSearch_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnAirportSearch_2.setObjectName("btnAirportSearch_2")
        self.gridLayout.addWidget(self.btnAirportSearch_2, 3, 5, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.btnAirportSearch = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnAirportSearch.setObjectName("btnAirportSearch")
        self.gridLayout.addWidget(self.btnAirportSearch, 2, 5, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.btnBookFlight = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnBookFlight.setObjectName("btnBookFlight")
        self.gridLayout.addWidget(self.btnBookFlight, 8, 5, 1, 1)
        self.btnSearchFlight = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnSearchFlight.setObjectName("btnSearchFlight")
        self.gridLayout.addWidget(self.btnSearchFlight, 8, 4, 1, 1)
        self.txtFrom = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txtFrom.setReadOnly(True)
        self.txtFrom.setObjectName("txtFrom")
        self.gridLayout.addWidget(self.txtFrom, 2, 1, 1, 4)
        self.txtDestination = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txtDestination.setReadOnly(True)
        self.txtDestination.setObjectName("txtDestination")
        self.gridLayout.addWidget(self.txtDestination, 3, 1, 1, 4)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 1, 1, 1)
        self.departureDate = QtWidgets.QDateEdit(self.gridLayoutWidget)
        self.departureDate.setCalendarPopup(True)
        self.departureDate.setObjectName("departureDate")
        self.gridLayout.addWidget(self.departureDate, 4, 2, 1, 3)
        self.returnDate = QtWidgets.QDateEdit(self.gridLayoutWidget)
        self.returnDate.setCalendarPopup(True)
        self.returnDate.setObjectName("returnDate")
        self.gridLayout.addWidget(self.returnDate, 5, 2, 1, 3)
        self.flightsTable = QtWidgets.QTableWidget(self.gridLayoutWidget)
        self.flightsTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.flightsTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.flightsTable.setObjectName("flightsTable")
        self.flightsTable.setColumnCount(10)
        self.flightsTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.flightsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.flightsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.flightsTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.flightsTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.flightsTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.flightsTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.flightsTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.flightsTable.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.flightsTable.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.flightsTable.setHorizontalHeaderItem(9, item)
        self.gridLayout.addWidget(self.flightsTable, 7, 0, 1, 6)
        self.btnManager = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnManager.setObjectName("btnManager")
        self.gridLayout.addWidget(self.btnManager, 8, 3, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DSC"))
        self.groupBox.setTitle(_translate("MainWindow", "User Information"))
        self.label_7.setText(_translate("MainWindow", "Date of Birth:"))
        self.dobLabel.setText(_translate("MainWindow", "null"))
        self.label_5.setText(_translate("MainWindow", "Full Name:"))
        self.label_6.setText(_translate("MainWindow", "User ID:"))
        self.nameLabel.setText(_translate("MainWindow", "null"))
        self.idLabel.setText(_translate("MainWindow", "null"))
        item = self.recentFlightsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Recent Flights"))
        self.label_8.setText(_translate("MainWindow", "Flyer Miles:"))
        self.pointsLabel.setText(_translate("MainWindow", "null"))
        self.btnAirportSearch_2.setText(_translate("MainWindow", "Search"))
        self.label_2.setText(_translate("MainWindow", "Destination:"))
        self.btnAirportSearch.setText(_translate("MainWindow", "Search"))
        self.label.setText(_translate("MainWindow", "From:"))
        self.btnBookFlight.setText(_translate("MainWindow", "Book Flight"))
        self.btnSearchFlight.setText(_translate("MainWindow", "Search Flights"))
        self.label_3.setText(_translate("MainWindow", "Departure Date:"))
        self.label_4.setText(_translate("MainWindow", "Return Date: "))
        item = self.flightsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Airline"))
        item = self.flightsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Price"))
        item = self.flightsTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Class"))
        item = self.flightsTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Depart Duration"))
        item = self.flightsTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Depart Take-off"))
        item = self.flightsTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Depart Landing"))
        item = self.flightsTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Return Duration"))
        item = self.flightsTable.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Return Take-off"))
        item = self.flightsTable.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Return Landing"))
        item = self.flightsTable.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Layover"))
        self.btnManager.setText(_translate("MainWindow", "Manager Panel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Flights"))

