#-------------------------------------------------------------------------------
# Name:        DSCTravelAgency
# Purpose:     Allows clients of a travel agency to book a flight.
#
# Author:      Kenta Iwasaki
#
# Created:     29/05/2014
# Copyright:   (c) Kenta Iwasaki 2014
# Licence:     N/A
#-------------------------------------------------------------------------------

# PyQT Imports
from PyQt5 import QtCore, QtGui, QtWidgets

# UI Layout and Setup
class Ui_OrderDialog(object):
    def setupUi(self, OrderDialog):
        OrderDialog.setObjectName("OrderDialog")
        OrderDialog.resize(399, 472)
        self.gridLayoutWidget = QtWidgets.QWidget(OrderDialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 381, 178))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 7, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 3)
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 2, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.txtCcNumber = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txtCcNumber.setObjectName("txtCcNumber")
        self.gridLayout.addWidget(self.txtCcNumber, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.txtCcType = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.txtCcType.setObjectName("txtCcType")
        self.txtCcType.addItem("")
        self.txtCcType.addItem("")
        self.txtCcType.addItem("")
        self.txtCcType.addItem("")
        self.gridLayout.addWidget(self.txtCcType, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.txtBillingAddress = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txtBillingAddress.setObjectName("txtBillingAddress")
        self.gridLayout.addWidget(self.txtBillingAddress, 6, 2, 1, 1)
        self.txtBillingName = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txtBillingName.setObjectName("txtBillingName")
        self.gridLayout.addWidget(self.txtBillingName, 5, 2, 1, 1)
        self.txtPhone = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txtPhone.setObjectName("txtPhone")
        self.gridLayout.addWidget(self.txtPhone, 7, 2, 1, 1)
        self.FlightInformation = QtWidgets.QGroupBox(OrderDialog)
        self.FlightInformation.setGeometry(QtCore.QRect(10, 200, 381, 231))
        self.FlightInformation.setObjectName("FlightInformation")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.FlightInformation)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 361, 201))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.txtReturnLanding = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.txtReturnLanding.setEnabled(True)
        self.txtReturnLanding.setReadOnly(True)
        self.txtReturnLanding.setObjectName("txtReturnLanding")
        self.gridLayout_2.addWidget(self.txtReturnLanding, 6, 1, 1, 1)
        self.txtAirline = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.txtAirline.setEnabled(True)
        self.txtAirline.setReadOnly(True)
        self.txtAirline.setObjectName("txtAirline")
        self.gridLayout_2.addWidget(self.txtAirline, 0, 1, 1, 1)
        self.txtDepartTakeoff = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.txtDepartTakeoff.setEnabled(True)
        self.txtDepartTakeoff.setReadOnly(True)
        self.txtDepartTakeoff.setObjectName("txtDepartTakeoff")
        self.gridLayout_2.addWidget(self.txtDepartTakeoff, 3, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 2, 0, 1, 1)
        self.txtDepartLanding = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.txtDepartLanding.setEnabled(True)
        self.txtDepartLanding.setReadOnly(True)
        self.txtDepartLanding.setObjectName("txtDepartLanding")
        self.gridLayout_2.addWidget(self.txtDepartLanding, 4, 1, 1, 1)
        self.txtReturnTakeoff = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.txtReturnTakeoff.setEnabled(True)
        self.txtReturnTakeoff.setReadOnly(True)
        self.txtReturnTakeoff.setObjectName("txtReturnTakeoff")
        self.gridLayout_2.addWidget(self.txtReturnTakeoff, 5, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 6, 0, 1, 1)
        self.txtPrice = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.txtPrice.setEnabled(True)
        self.txtPrice.setReadOnly(True)
        self.txtPrice.setObjectName("txtPrice")
        self.gridLayout_2.addWidget(self.txtPrice, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 1, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 5, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 4, 0, 1, 1)
        self.txtClass = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.txtClass.setEnabled(True)
        self.txtClass.setReadOnly(True)
        self.txtClass.setObjectName("txtClass")
        self.gridLayout_2.addWidget(self.txtClass, 2, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 3, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 7, 0, 1, 1)
        self.txtLayover = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.txtLayover.setReadOnly(True)
        self.txtLayover.setObjectName("txtLayover")
        self.gridLayout_2.addWidget(self.txtLayover, 7, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(OrderDialog)
        self.pushButton.setGeometry(QtCore.QRect(10, 440, 381, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(OrderDialog)
        QtCore.QMetaObject.connectSlotsByName(OrderDialog)

    def retranslateUi(self, OrderDialog):
        _translate = QtCore.QCoreApplication.translate
        OrderDialog.setWindowTitle(_translate("OrderDialog", "DSC :: Order Confirmation"))
        self.label_5.setText(_translate("OrderDialog", "Billing Address:"))
        self.label_6.setText(_translate("OrderDialog", "Phone Number:"))
        self.label_3.setText(_translate("OrderDialog", "Credit Card CVC:"))
        self.label_2.setText(_translate("OrderDialog", "Credit Card Number:"))
        self.txtCcNumber.setText(_translate("OrderDialog", "0000-0000-0000-0000"))
        self.label.setText(_translate("OrderDialog", "Credit Card Type:"))
        self.txtCcType.setItemText(0, _translate("OrderDialog", "VISA"))
        self.txtCcType.setItemText(1, _translate("OrderDialog", "Mastercard"))
        self.txtCcType.setItemText(2, _translate("OrderDialog", "American Express"))
        self.txtCcType.setItemText(3, _translate("OrderDialog", "Discover"))
        self.label_4.setText(_translate("OrderDialog", "Billing Name:"))
        self.FlightInformation.setTitle(_translate("OrderDialog", "Flight Information"))
        self.label_9.setText(_translate("OrderDialog", "Airplane Class:"))
        self.label_13.setText(_translate("OrderDialog", "Return Landing:"))
        self.label_7.setText(_translate("OrderDialog", "Airline Name:"))
        self.label_8.setText(_translate("OrderDialog", "Trip Price:"))
        self.label_12.setText(_translate("OrderDialog", "Return Takeoff:"))
        self.label_11.setText(_translate("OrderDialog", "Depart Landing:"))
        self.label_10.setText(_translate("OrderDialog", "Depart Takeoff:"))
        self.label_14.setText(_translate("OrderDialog", "Layover:"))
        self.pushButton.setText(_translate("OrderDialog", "Purchase"))

